INSERT INTO CURRENCY_EXCHANGE
(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO)
VALUES
(1000,65,'USD','INR');

INSERT INTO CURRENCY_EXCHANGE
(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO)
VALUES
(1001,75,'EUR','INR');

INSERT INTO CURRENCY_EXCHANGE
(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO)
VALUES
(1002,25,'CAD','INR');

INSERT INTO CURRENCY_EXCHANGE
(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO)
VALUES
(1003,27,'AUD','INR');

INSERT INTO CURRENCY_EXCHANGE
(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO)
VALUES
(1004,4,'MXN','INR');
